{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "efba5e73",
   "metadata": {},
   "source": [
    "# Caso 2: Dashboard Financiero y Scraping\n",
    "### Nombre: Marco Sebastian Ocampo y Javier Hernández\n",
    "### Fecha: 7 de noviembre del 2023"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "73434869",
   "metadata": {},
   "outputs": [],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from selenium.webdriver.support.ui import Select\n",
    "from selenium.webdriver.common.by import By\n",
    "from datetime import datetime\n",
    "import dash\n",
    "\n",
    "from dash import dcc\n",
    "from dash import html\n",
    "from dash import dash_table\n",
    "from dash.dependencies import Input, Output\n",
    "import plotly.express as px\n",
    "import pandas as pd\n",
    "import dash_bootstrap_components as dbc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ceec2a86",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Country Name</th>\n",
       "      <th>Time</th>\n",
       "      <th>PIB</th>\n",
       "      <th>CRECIMIENTO</th>\n",
       "      <th>IPC</th>\n",
       "      <th>Unnamed: 5</th>\n",
       "      <th>Unnamed: 6</th>\n",
       "      <th>Unnamed: 7</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Belize</td>\n",
       "      <td>2008</td>\n",
       "      <td>1879425113</td>\n",
       "      <td>-1.519916</td>\n",
       "      <td>100.196857</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Belize</td>\n",
       "      <td>2009</td>\n",
       "      <td>1870923190</td>\n",
       "      <td>-0.452368</td>\n",
       "      <td>99.090373</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Belize</td>\n",
       "      <td>2010</td>\n",
       "      <td>1894428507</td>\n",
       "      <td>1.256349</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Belize</td>\n",
       "      <td>2011</td>\n",
       "      <td>1892428054</td>\n",
       "      <td>-0.105597</td>\n",
       "      <td>101.602056</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Belize</td>\n",
       "      <td>2012</td>\n",
       "      <td>1965444570</td>\n",
       "      <td>3.858351</td>\n",
       "      <td>102.923473</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Country Name  Time         PIB  CRECIMIENTO         IPC  Unnamed: 5  \\\n",
       "0       Belize  2008  1879425113    -1.519916  100.196857         NaN   \n",
       "1       Belize  2009  1870923190    -0.452368   99.090373         NaN   \n",
       "2       Belize  2010  1894428507     1.256349  100.000000         NaN   \n",
       "3       Belize  2011  1892428054    -0.105597  101.602056         NaN   \n",
       "4       Belize  2012  1965444570     3.858351  102.923473         NaN   \n",
       "\n",
       "   Unnamed: 6 Unnamed: 7  \n",
       "0         NaN        NaN  \n",
       "1         NaN        NaN  \n",
       "2         NaN        NaN  \n",
       "3         NaN        NaN  \n",
       "4         NaN        NaN  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dfc= pd.read_csv(\"CENTROA.csv\")\n",
    "dfc.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "66125a2a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#establcer carpeta donde va a guardar el archivo \n",
    "options= webdriver.ChromeOptions()\n",
    "prefs = {\"download.default_directory\": r\"C:\\Users\\Marco\\Documents\\Segundo Semestre 2023\\Data Science for Finance\"}\n",
    "options.add_experimental_option(\"prefs\",prefs)\n",
    "#descargar driver, extraerlo y ponerlo en la carpeta seleccionada arriba\n",
    "#https://googlechromelabs.github.io/chrome-for-testing/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "e319baa0",
   "metadata": {},
   "outputs": [],
   "source": [
    "### INFLACION\n",
    "s=Service(r\"C:\\Users\\Marco\\Documents\\Segundo Semestre 2023\\Data Science for Finance\\chromedriver.exe\")\n",
    "driver=webdriver.Chrome(service=s,options=options)\n",
    "#determinar la pagina de la que queremos hacer el scraping\n",
    "driver.get(\"https://www.banguat.gob.gt/es/page/inflacion-total/\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "9417a26c",
   "metadata": {},
   "outputs": [],
   "source": [
    "driver.find_element(\"xpath\",\n",
    "                    \"/html/body/div[2]/div[1]/div/section/div/div/div/div/article/div/div[2]/p[2]/a\").click()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "236b7cfa",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Año</th>\n",
       "      <th>Mes</th>\n",
       "      <th>Inflacion</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1996</td>\n",
       "      <td>Enero</td>\n",
       "      <td>9.76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1996</td>\n",
       "      <td>Febrero</td>\n",
       "      <td>10.83</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1996</td>\n",
       "      <td>Marzo</td>\n",
       "      <td>11.48</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1996</td>\n",
       "      <td>Abril</td>\n",
       "      <td>11.95</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1996</td>\n",
       "      <td>Mayo</td>\n",
       "      <td>11.02</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Año      Mes  Inflacion\n",
       "0  1996    Enero       9.76\n",
       "1  1996  Febrero      10.83\n",
       "2  1996    Marzo      11.48\n",
       "3  1996    Abril      11.95\n",
       "4  1996     Mayo      11.02"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "### DATA DE INFLACION\n",
    "dfi = pd.read_excel('INFLACION.xlsx')\n",
    "dfi.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "24cbc5d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "### TASA DE INTERES\n",
    "s=Service(r\"C:\\Users\\Marco\\Documents\\Segundo Semestre 2023\\Data Science for Finance\\chromedriver.exe\")\n",
    "driver=webdriver.Chrome(service=s,options=options)\n",
    "#determinar la pagina de la que queremos hacer el scraping\n",
    "driver.get(\"https://www.banguat.gob.gt/page/activa\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "672cff36",
   "metadata": {},
   "outputs": [],
   "source": [
    "driver.find_element(\"xpath\",\n",
    "                    \"/html/body/div[2]/div[1]/div/section/div/div/div/div/article/div/div[2]/p[2]/a\").click()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ab312a07",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Mes/Año</th>\n",
       "      <th>1996</th>\n",
       "      <th>1997</th>\n",
       "      <th>1998</th>\n",
       "      <th>1999</th>\n",
       "      <th>2000</th>\n",
       "      <th>2001</th>\n",
       "      <th>2002</th>\n",
       "      <th>2003</th>\n",
       "      <th>2004</th>\n",
       "      <th>...</th>\n",
       "      <th>2014</th>\n",
       "      <th>2015</th>\n",
       "      <th>2016</th>\n",
       "      <th>2017</th>\n",
       "      <th>2018</th>\n",
       "      <th>2019</th>\n",
       "      <th>2020</th>\n",
       "      <th>2021</th>\n",
       "      <th>2022</th>\n",
       "      <th>2023</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Enero</td>\n",
       "      <td>0.222</td>\n",
       "      <td>0.2198</td>\n",
       "      <td>0.1616</td>\n",
       "      <td>0.1781</td>\n",
       "      <td>0.2123</td>\n",
       "      <td>0.1992</td>\n",
       "      <td>0.1771</td>\n",
       "      <td>0.1601</td>\n",
       "      <td>0.1400</td>\n",
       "      <td>...</td>\n",
       "      <td>0.1378</td>\n",
       "      <td>0.1360</td>\n",
       "      <td>0.1308</td>\n",
       "      <td>0.1305</td>\n",
       "      <td>0.1307</td>\n",
       "      <td>0.1274</td>\n",
       "      <td>0.1265</td>\n",
       "      <td>0.1234</td>\n",
       "      <td>0.1192</td>\n",
       "      <td>0.1189</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Febrero</td>\n",
       "      <td>0.226</td>\n",
       "      <td>0.2121</td>\n",
       "      <td>0.1620</td>\n",
       "      <td>0.1871</td>\n",
       "      <td>0.2139</td>\n",
       "      <td>0.1988</td>\n",
       "      <td>0.1750</td>\n",
       "      <td>0.1584</td>\n",
       "      <td>0.1393</td>\n",
       "      <td>...</td>\n",
       "      <td>0.1381</td>\n",
       "      <td>0.1348</td>\n",
       "      <td>0.1307</td>\n",
       "      <td>0.1305</td>\n",
       "      <td>0.1305</td>\n",
       "      <td>0.1277</td>\n",
       "      <td>0.1268</td>\n",
       "      <td>0.1232</td>\n",
       "      <td>0.1192</td>\n",
       "      <td>0.1194</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Marzo</td>\n",
       "      <td>0.224</td>\n",
       "      <td>0.2081</td>\n",
       "      <td>0.1637</td>\n",
       "      <td>0.1890</td>\n",
       "      <td>0.2128</td>\n",
       "      <td>0.1958</td>\n",
       "      <td>0.1722</td>\n",
       "      <td>0.1561</td>\n",
       "      <td>0.1389</td>\n",
       "      <td>...</td>\n",
       "      <td>0.1380</td>\n",
       "      <td>0.1337</td>\n",
       "      <td>0.1311</td>\n",
       "      <td>0.1308</td>\n",
       "      <td>0.1301</td>\n",
       "      <td>0.1279</td>\n",
       "      <td>0.1264</td>\n",
       "      <td>0.1232</td>\n",
       "      <td>0.1195</td>\n",
       "      <td>0.1193</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Abril</td>\n",
       "      <td>0.227</td>\n",
       "      <td>0.1997</td>\n",
       "      <td>0.1614</td>\n",
       "      <td>0.1886</td>\n",
       "      <td>0.2144</td>\n",
       "      <td>0.1942</td>\n",
       "      <td>0.1721</td>\n",
       "      <td>0.1549</td>\n",
       "      <td>0.1397</td>\n",
       "      <td>...</td>\n",
       "      <td>0.1381</td>\n",
       "      <td>0.1329</td>\n",
       "      <td>0.1313</td>\n",
       "      <td>0.1308</td>\n",
       "      <td>0.1302</td>\n",
       "      <td>0.1275</td>\n",
       "      <td>0.1262</td>\n",
       "      <td>0.1228</td>\n",
       "      <td>0.1193</td>\n",
       "      <td>0.1193</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Mayo</td>\n",
       "      <td>0.229</td>\n",
       "      <td>0.1935</td>\n",
       "      <td>0.1621</td>\n",
       "      <td>0.1902</td>\n",
       "      <td>0.2146</td>\n",
       "      <td>0.1923</td>\n",
       "      <td>0.1711</td>\n",
       "      <td>0.1512</td>\n",
       "      <td>0.1393</td>\n",
       "      <td>...</td>\n",
       "      <td>0.1383</td>\n",
       "      <td>0.1321</td>\n",
       "      <td>0.1315</td>\n",
       "      <td>0.1304</td>\n",
       "      <td>0.1298</td>\n",
       "      <td>0.1274</td>\n",
       "      <td>0.1266</td>\n",
       "      <td>0.1225</td>\n",
       "      <td>0.1194</td>\n",
       "      <td>0.1198</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 29 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Mes/Año   1996    1997    1998    1999    2000    2001    2002    2003  \\\n",
       "0      Enero  0.222  0.2198  0.1616  0.1781  0.2123  0.1992  0.1771  0.1601   \n",
       "1    Febrero  0.226  0.2121  0.1620  0.1871  0.2139  0.1988  0.1750  0.1584   \n",
       "2      Marzo  0.224  0.2081  0.1637  0.1890  0.2128  0.1958  0.1722  0.1561   \n",
       "3      Abril  0.227  0.1997  0.1614  0.1886  0.2144  0.1942  0.1721  0.1549   \n",
       "4       Mayo  0.229  0.1935  0.1621  0.1902  0.2146  0.1923  0.1711  0.1512   \n",
       "\n",
       "     2004  ...    2014    2015    2016    2017    2018    2019    2020  \\\n",
       "0  0.1400  ...  0.1378  0.1360  0.1308  0.1305  0.1307  0.1274  0.1265   \n",
       "1  0.1393  ...  0.1381  0.1348  0.1307  0.1305  0.1305  0.1277  0.1268   \n",
       "2  0.1389  ...  0.1380  0.1337  0.1311  0.1308  0.1301  0.1279  0.1264   \n",
       "3  0.1397  ...  0.1381  0.1329  0.1313  0.1308  0.1302  0.1275  0.1262   \n",
       "4  0.1393  ...  0.1383  0.1321  0.1315  0.1304  0.1298  0.1274  0.1266   \n",
       "\n",
       "     2021    2022    2023  \n",
       "0  0.1234  0.1192  0.1189  \n",
       "1  0.1232  0.1192  0.1194  \n",
       "2  0.1232  0.1195  0.1193  \n",
       "3  0.1228  0.1193  0.1193  \n",
       "4  0.1225  0.1194  0.1198  \n",
       "\n",
       "[5 rows x 29 columns]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "### DATA DE TASA DE INTERES\n",
    "dfi = pd.read_excel('TASA DE INTERES.xlsx')\n",
    "dfi.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "e9004df3",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:2847/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x1ba8fd64f10>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "app2 = dash.Dash(__name__)\n",
    "\n",
    "# Define el diseño de la aplicación\n",
    "app2.layout = html.Div([\n",
    "    html.H4(\"Variación de los indicadores de Centro América\"),\n",
    "    html.P(\"País:\"),\n",
    "    dcc.Checklist(\n",
    "        id=\"x-axis\",\n",
    "        options=[\n",
    "            {'label': 'Guatemala', 'value': 'Guatemala'},\n",
    "            {'label': 'Belize', 'value': 'Belize'},\n",
    "            {'label': 'El Salvador', 'value': 'El Salvador'},\n",
    "            {'label': 'Honduras', 'value': 'Honduras'},\n",
    "            {'label': 'Nicaragua', 'value': 'Nicaragua'},\n",
    "            {'label': 'Costa Rica', 'value': 'Costa Rica'},\n",
    "            {'label': 'Panama', 'value': 'Panama'}\n",
    "        ],\n",
    "        value=['Guatemala'],\n",
    "        inline=True\n",
    "    ),\n",
    "    html.P(\"Indicador:\"),\n",
    "    dcc.RadioItems(\n",
    "        id=\"y-axis\",\n",
    "        options=[\n",
    "            {'label': 'CRECIMIENTO', 'value': 'CRECIMIENTO'},\n",
    "            {'label': 'PIB', 'value': 'PIB'},\n",
    "            {'label': 'IPC', 'value': 'IPC'}\n",
    "        ],\n",
    "        value='PIB',\n",
    "        inline=True\n",
    "    ),\n",
    "    dcc.Graph(id=\"graph\"),\n",
    "    html.P(\"Tipo de gráfico:\"),\n",
    "    dcc.RadioItems(\n",
    "        id=\"chart-type\",\n",
    "        options=[\n",
    "            {'label': 'Boxplot', 'value': 'boxplot'},\n",
    "            {'label': 'Líneas', 'value': 'lines'},\n",
    "            {'label': 'Proporción', 'value': 'pie'}\n",
    "        ],\n",
    "        value='boxplot',\n",
    "        inline=True\n",
    "    ),\n",
    "    html.Div(id=\"year-selector-container\")  # Contenedor para el selector de año\n",
    "])\n",
    "\n",
    "# Callback para actualizar el gráfico y la selección de año\n",
    "@app2.callback(\n",
    "    Output(\"graph\", \"figure\"),\n",
    "    Output(\"year-selector-container\", \"children\"),  # Muestra u oculta el selector de año\n",
    "    Input(\"x-axis\", \"value\"),\n",
    "    Input(\"y-axis\", \"value\"),\n",
    "    Input(\"chart-type\", \"value\")\n",
    ")\n",
    "def generate_chart(selected_countries, selected_indicator, chart_type):\n",
    "    filtered_df = dfc[dfc['Country Name'].isin(selected_countries)]\n",
    "\n",
    "    if chart_type == 'boxplot':\n",
    "        # Personalizar la paleta de colores\n",
    "        colors = ['#33FF57', '#5733FF', '#33FFFF', '#FF33FF']\n",
    "        fig = px.box(filtered_df, x='Country Name', y=selected_indicator, title=f'Boxplot de {selected_indicator}',\n",
    "                     color_discrete_sequence=colors)\n",
    "        year_selector = []  # No mostrar el selector de año\n",
    "    elif chart_type == 'lines':\n",
    "        colors1 = ['#FF5733', '#33FF57', '#5733FF', '#33FFFF', '#FF33FF']\n",
    "        fig = px.line(filtered_df, x='Time', y=selected_indicator, title=f'Gráfico de Líneas de {selected_indicator}',\n",
    "                      color_discrete_sequence=colors1)\n",
    "        year_selector = []  # No mostrar el selector de año\n",
    "    else:\n",
    "        colors1 = ['#FF5733', '#33FF57', '#5733FF', '#33FFFF', '#FF33FF']\n",
    "        fig = px.pie(filtered_df, names='Country Name', values=selected_indicator, title=f'Gráfico de Pastel de {selected_indicator}',\n",
    "                      color_discrete_sequence=colors1)\n",
    "        year_selector = dcc.Dropdown(\n",
    "            id=\"year-selector\",\n",
    "            options=[\n",
    "                {'label': str(year), 'value': year}\n",
    "                for year in range(2000, 2023)  # Rango de años a seleccionar\n",
    "            ],\n",
    "            value=2022,  # Año inicial seleccionado\n",
    "            clearable=False,\n",
    "        )\n",
    "    \n",
    "    return fig, year_selector\n",
    "\n",
    "# Ejecuta la aplicación\n",
    "if __name__ == '__main__':\n",
    "    app2.run_server(debug=True, port=2847)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "d9dff0f9",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:2240/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x1ba95819190>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Construir el dashboard\n",
    "app = dash.Dash(__name__)\n",
    "\n",
    "cuentas = [\"Inflacion\"]\n",
    "\n",
    "# Layout del app\n",
    "app.layout = html.Div([\n",
    "    html.Div([html.Div([\n",
    "        # Primer drop down para elegir año.\n",
    "        html.Div(dcc.Dropdown(\n",
    "            id=\"Inflacion_año\", value=[\"2019\", \"2020\", \"2021\", \"2022\", \"2023\"], clearable=False, multi=True,\n",
    "            options=[{'label': x, 'value': x} for x in sorted(dfi.Año.unique())]\n",
    "        ), className=\"six columns\", style={\"width\": \"50%\"},),\n",
    "\n",
    "        # Segundo drop down\n",
    "        html.Div(dcc.Dropdown(\n",
    "            id=\"Inflacion_total\", value=\"Inflacion\", clearable=False,\n",
    "            options=[{'label': x, 'value': x} for x in cuentas]\n",
    "        ), className=\"six columns\"),\n",
    "    ], className=\"row\"),], className=\"custom-dropdown\"),\n",
    "\n",
    "    # Gráficas\n",
    "    html.Div([dcc.Graph(id=\"graph\", figure={}, config={\"displayModeBar\": True, \"displaylogo\": False,\n",
    "                                                       # \"modeBarButtonsToRemove\":['pan2d','lasso2d',\n",
    "                                                       #                         'select2d']\n",
    "                                                       })], style={'width': '1100px'}),\n",
    "    html.Div([dcc.Graph(id=\"boxplot\", figure={})], style={\"width\": \"1100px\"}),\n",
    "\n",
    "    # Tabla\n",
    "    html.Div(html.Div(id=\"table-container\"), style={'marginBottom': '15px', 'marginTop': \"10px\"}),\n",
    "])\n",
    "\n",
    "# Callback de la función\n",
    "@app.callback(\n",
    "    [Output(component_id=\"graph\", component_property=\"figure\"),\n",
    "     Output(component_id=\"boxplot\", component_property=\"figure\"),\n",
    "     Output(\"table-container\", 'children')],\n",
    "    [Input(component_id=\"Inflacion_año\", component_property=\"value\"),\n",
    "     Input(component_id=\"Inflacion_total\", component_property=\"value\")]\n",
    ")\n",
    "# Definición de la función\n",
    "def display_value(selected_año, selected_mes):\n",
    "    if len(selected_año) == 0:\n",
    "        df2 = dfi[dfi[\"Año\"].isin([\"2019\", \"2020\", \"2021\", \"2022\", \"2023\"])]\n",
    "    else:\n",
    "        df2 = dfi[dfi[\"Año\"].isin(selected_año)]\n",
    "\n",
    "    # Gráfica 1\n",
    "    fig = px.line(df2, color=\"Año\", x=\"Mes\", markers=True, y=selected_mes, width=1000, height=500)\n",
    "\n",
    "    fig.update_layout(title=f'{selected_mes} de {selected_año}', xaxis_title=\"Inflacion Mensual\")\n",
    "    fig.update_traces(line=dict(width=2))\n",
    "\n",
    "    # Gráfica 2\n",
    "    fig2 = px.box(df2, color=\"Año\", x=\"Año\", y=selected_mes, width=1000, height=500)\n",
    "    fig2.update_layout(title=f'{selected_mes} de {selected_año}')\n",
    "\n",
    "    # Modificar DataFrame para poder hacerlo tabla\n",
    "    df_reshaped = df2.pivot(index='Año', columns='Mes', values=selected_mes)\n",
    "    df_reshaped_3 = df_reshaped.reset_index()\n",
    "\n",
    "    # Tabla\n",
    "    return (fig, fig2, dash_table.DataTable(columns=[{\"name\": i, \"id\": i} for i in df_reshaped_3],\n",
    "                                           data=df_reshaped_3.to_dict(\"records\"),\n",
    "                                           export_format=\"csv\",\n",
    "                                           fill_width=True,\n",
    "                                           style_header={'backgroundColor': 'blue', 'color': 'white'}))\n",
    "\n",
    "# Setear server y correr\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(port=2240)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
